### ISSUE TITLE
Folding directories

### ISSUE THREAD

**Issue by duikboot** [mhinz/vim-tree#1]
Hi,

Thanks for your plugin, it's really nice.
I think the ability to fold the directories would be very useful.

**Comment by mhinz** [comment]
This should be very doable. :+1:

**Comment by mhinz** [comment]
Please update and see if you see what you expected when doing `:setl fdm=expr`.

**Comment by duikboot** [comment]
Nice, that's really cool. Thanks a lot!

**Comment by mhinz** [comment]
I also changed <kbd>l</kbd> and <kbd>h</kbd> to open and close folds respectively.
